MOTC/MOTC/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MOTC.Data.Services;

namespace MOTC.Controllers
{
    public class DetailsController : Controller
    {
        private readonly IMoviesRepo _movieRepo;

        public DetailsController(IMoviesRepo movieRepo)
        {
            _movieRepo = movieRepo;
        }
        public IActionResult MovieDetails(int Id)
        {
            var movieResult = _movieRepo.GetById(Id);
            if (movieResult != null)
            {
                return View(movieResult);
            }
                return View(null);
        }
    }
}

MOTC/MOTC/Views/Shared/_ImageGrid.cshtml
@model MOTC.Core.Models.MoviesModel

@{
    var imgPath = "~/images/movies/" + (Model.ImagePath ?? "noImage.png");
}
<div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <a asp-controller="Details" asp-action="MovieDetails" asp-route-id="@Model.Id" }>
                <img class="card-img" src="@imgPath" asp-append-version="true" />
                </a>
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">  @Model.Name  </h5>
                <h6>Genre: @Model.Genre </h6>
                <br />
                <br />
                <br />
                <a href="#">
                    <i class="btn btn-warning">Add to Cart</i>
                </a>
            </div>
        </div>
    </div>
</div>

MOTC/MOTC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MOTC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav style=" background-color: #333;
    text-align: center;
    color: #eee;">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" style="color:white;">
                Admin
            </a>
        </nav>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-transparent border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="img-thumbnail" src="~/images/logo.jpg" />
                    MOTC
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LogIn">Log-in</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse justify-content-between">
                    <ul class="navbar-nav flex-grow-0">
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="#">
                                <i class="btn btn-primary">Cart</i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MOTC/MOTC/Views/Shared/_Slider.cshtml
<style>
    img {
        max-width: 100%;
        height: 450px;
        margin-left: 0;
    }

    .carousel-inner {
        background-color: lightslategray !important;
    }
</style>
<h4>Trending Now</h4>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" >
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" >
        <div class="carousel-item active">
            <img src="~/images/Slider/Slides.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/images/Slider/slideMI.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/images/Slider/Slidess3.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

MOTC/MOTC/Views/Shared/_categoryView.cshtml
@model string

<div class="card mt-4" style="width: 18rem;float:left;text-align:center;margin:10px;">
    <div class="card-body">
            <h3 class="card-title">
                            @Html.ActionLink(Model, "Category","Home", new { genre = Model })
                </h3>
    </div>
</div>

MOTC/MOTC/Views/Shared/_imageView.cshtml
@model MOTC.Core.Models.MoviesModel

@{
    var imgPath = "~/images/movies/" + (Model.ImagePath ?? "noImage.png");
}
    <style>
        div.gallery {
            margin: 5px;
            border: 1px solid #ccc;
            float: left;
            width: 260px;
        }

            div.gallery:hover {
                border: 1px solid #777;
            }

            div.gallery img {
                width: 100%;
                height: 250px;
            }

        div.desc {
            padding: 15px;
            text-align: center;
        }
    </style>
<div class="gallery">
    <a asp-controller="Details" asp-action="MovieDetails" asp-route-id = "@Model.Id" }>
        <img src="@imgPath" alt="Cinque Terre" width="800" height="600" class="card-img-top" alt="..." asp-append-version="true">
        </a>
        <div class="desc">
            <h5 class="card-title">  @Model.Name  </h5>
            <p class="card-text">  Genre: @Model.Genre </p>
            <a href="#">
                <i class="btn btn-warning">Add to Cart</i>
            </a>
        </div>
</div>